version: '3.8'

services:
  linkedin-bot:
    build: .
    volumes:
      - chrome_data:/home/user/chrome_data  # This will be the persistent volume for Chrome user data
    environment:
      - PYTHONUNBUFFERED=1
    # user: "user"  # To ensure we run as the unprivileged user you created in your Dockerfile

volumes:
  chrome_data:  # This volume will store Chrome user data persistently
